import 'dart:convert';
import 'dart:io';

import 'package:recase/recase.dart';

void main(List<String> arguments) {
  var file = new File(arguments.first);

  if (!file.existsSync()) {
    print('Cannot find the file "${arguments.first}".');
  }

  var content = file.readAsStringSync();
  Map<String, dynamic> icons = json.decode(content);

  Map<String, String> iconDefinitions = {};

  for (String iconName in icons.keys) {
    var icon = icons[iconName];
    var unicode = icon['unicode'];
    List<String> styles = (icon['styles'] as List).cast<String>();

    if (styles.length > 1) {
      if (styles.contains('regular')) {
        styles.remove('regular');
        iconDefinitions[iconName] = generateIconDefinition(
          iconName,
          'regular',
          unicode,
        );
      }

      for (String style in styles) {
        String name = '${style}_$iconName';
        iconDefinitions[name] = generateIconDefinition(
          name,
          styles.first,
          unicode,
        );
      }
    } else {
      iconDefinitions[iconName] = generateIconDefinition(
        iconName,
        styles.first,
        unicode,
      );
    }
  }

  List<String> generatedOutput = [
    'library font_awesome_flutter;',
    '',
    "import 'package:flutter/widgets.dart';",
    "import 'package:font_awesome_flutter/icon_data.dart';",
    '',
    '// THIS FILE IS AUTOMATICALLY GENERATED!',
    '',
    'class FontAwesomeIcons {',
  ];

  generatedOutput.addAll(iconDefinitions.values);

  generatedOutput.add('}');

  File output = new File('lib/font_awesome_flutter.dart');
  output.writeAsStringSync(generatedOutput.join('\n'));


  List<String> generatedMapOutput = [
    'library font_awesome_flutter;',
    '',
    "import 'package:font_awesome_flutter/font_awesome_flutter.dart';",
    "import 'package:flutter/widgets.dart';",
    '',
    '// THIS FILE IS AUTOMATICALLY GENERATED!',
    'class FontAwesomeIconsMap {',
    ' static IconData fromString(String name){',
    '   return icons[name];',
    ' }',
    ' static Map<String, IconData> icons = {',
  ];

  generatedMapOutput.addAll(icons.keys.map(generateIconMapEntry));

  generatedMapOutput.add(' };');
  generatedMapOutput.add('}');

  File outputMap = new File('lib/font_awesome_flutter_map.dart');
  outputMap.writeAsStringSync(generatedMapOutput.join('\n'));
}

String generateIconDefinition(String iconName, String style, String unicode) {
  style = '${style[0].toUpperCase()}${style.substring(1)}';

  String iconDataSource = 'IconData$style';

  if (iconName == '500px') {
    iconName = 'fiveHundredPx';
  }

  iconName = new ReCase(iconName).camelCase;

  return 'static const IconData $iconName = const $iconDataSource(0x$unicode);';
}


String generateIconMapEntry(String iconName) {
  if (iconName == '500px') {
    iconName = 'fiveHundredPx';
  }

  iconName = new ReCase(iconName).camelCase;

  return '"$iconName" : FontAwesomeIcons.$iconName,';
}
