import 'dart:convert';
import 'dart:io';

void main(List<String> arguments) {
  var file = new File(arguments.first);

  if (!file.existsSync()) {
    print('Cannot find the file "${arguments.first}".');
  }

  var content = file.readAsStringSync();
  Map<String, dynamic> icons = json.decode(content);

  List<String> generatedOutput = [
    '',
    '// THIS FILE IS AUTOMATICALLY GENERATED!',
    '',
    'class FontAwesomeMap {',
    'static Map<String, int> map = {',
  ];

  for (String iconName in icons.keys) {
    var icon = icons[iconName];

    if (iconName == '500px') {
      iconName = 'fiveHundredPx';
    }

    var unicode = int.parse(icon['unicode'], radix: 16);

    generatedOutput.add("'$iconName': $unicode,");
  }

  generatedOutput.add('};}');

  File output = new File('lib/font_awesome_map.dart');
  output.writeAsStringSync(generatedOutput.join('\n'));
}
